version: "3.5"

services:
  postgres:
    container_name: chattin-messages-postgres
    image: postgres:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: chattin
      POSTGRES_PASSWORD: chattinmessages
      POSTGRES_DB: messages
    ports:
      - "5432:5432"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.7"
    #       memory: "1.5GB"

  redis:
    image: redis:latest
    container_name: chattin-message-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
